function Qr = ldrb_orient(Q, alpha, beta)
% Function 3 in supplement of Bayer 2012:
% https://doi.org/10.1007/s10439-012-0593-5

Qr = Q * [cos(alpha) -sin(alpha)  0; ...
          sin(alpha)  cos(alpha)  0; ...
          0           0           1] ...
       * [1           0           0; ...
          0           cos(beta)   sin(beta); ...
          0          -sin(beta)   cos(beta)];

end